# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/nscscc/cdp_ede_local-master/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/TAG_RAM/TAG_RAM.xci
# IP: The module: 'TAG_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nscscc/cdp_ede_local-master/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/TAG_RAM/TAG_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TAG_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/nscscc/cdp_ede_local-master/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.srcs/sources_1/ip/TAG_RAM/TAG_RAM.xci
# IP: The module: 'TAG_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/nscscc/cdp_ede_local-master/mycpu_env/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/TAG_RAM/TAG_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TAG_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
